DynamicListExample/Controllers/ParentController.cs
using DynamicListExample.Models;
using Microsoft.AspNetCore.Mvc;

namespace DynamicListExample.Controllers
{
    public class ParentController : Controller
    {
        public IActionResult GetChildPartialView()
        {
            // If this is throwing an error saying it can't resolve _ChildPartialView you can ignore it, works fine. Not present in VS2019 Version 16.4.5
            return PartialView("_ChildPartialView", new Child());
        }
    }
}

DynamicListExample/Pages/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DynamicListExample.Models;

namespace DynamicListExample.Pages
{
    public class CreateModel : PageModel
    {
        private readonly DynamicListExample.Data.ApplicationDbContext _context;

        [BindProperty]
        public Parent Parent { get; set; }

        public CreateModel(DynamicListExample.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Parents.Add(Parent);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

DynamicListExample/Pages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DynamicListExample.Data;
using DynamicListExample.Models;

namespace DynamicListExample.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly DynamicListExample.Data.ApplicationDbContext _context;

        public DeleteModel(DynamicListExample.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Parent Parent { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Parent = await _context.Parents.FirstOrDefaultAsync(m => m.Id == id);

            if (Parent == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Parent = await _context.Parents.FindAsync(id);

            if (Parent != null)
            {
                _context.Parents.Remove(Parent);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

DynamicListExample/Pages/Details.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DynamicListExample.Models;

namespace DynamicListExample.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly DynamicListExample.Data.ApplicationDbContext _context;

        public DetailsModel(DynamicListExample.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Parent Parent { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Parent = await _context.Parents
                .AsNoTracking()
                .Include(p => p.Children)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Parent == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

DynamicListExample/Pages/Edit.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DynamicListExample.Data;
using DynamicListExample.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace DynamicListExample.Pages
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Parent Parent { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Parent = await _context.Parents
                .Include(p => p.Children)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Parent == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Parent parent)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                var parentToUpdate = await _context.Parents
                    .Include(p => p.Children)
                    .SingleOrDefaultAsync(p => p.Id == parent.Id);

                if (parentToUpdate == null) return NotFound();

                // Update the Parent's name
                parentToUpdate.Name = parent.Name;

                // Save this to a list so when we remove something from parentToUpdate, it doesn't 
                // get mad at us for trying to further alter a modified collection
                var existingChildren = parentToUpdate.Children?.ToList();
                
                // Deteach Children from the Call Detail if they don't show up now
                if (existingChildren != null)
                {
                    foreach (var child in existingChildren)
                    {
                        if (parent.Children.FirstOrDefault(x => x.Id == child.Id) == null)
                        {
                            parentToUpdate.Children.Remove(child);
                        }
                    }
                }

                // Add or Update existing and new Children
                foreach (var child in parent.Children)
                {
                    var childToUpdate = parentToUpdate.Children?.FirstOrDefault(c => c.Id == child.Id);

                    if (childToUpdate != null)
                    {
                        childToUpdate.Name = child.Name;
                    }
                    else
                    {
                        parentToUpdate.Children?.Add(new Child
                        {
                            Name = child.Name,
                            ParentId = parent.Id
                        });
                    }
                }

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ParentExists(Parent.Id))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToPage("./Index");
        }

        private bool ParentExists(Guid id)
        {
            return _context.Parents.Any(e => e.Id == id);
        }
    }
}

DynamicListExample/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DynamicListExample.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DynamicListExample/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DynamicListExample.Data;
using DynamicListExample.Models;

namespace DynamicListExample.Pages
{
    public class IndexModel : PageModel
    {
        private readonly DynamicListExample.Data.ApplicationDbContext _context;

        public IndexModel(DynamicListExample.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Parent> Parent { get;set; }

        public async Task OnGetAsync()
        {
            Parent = await _context.Parents.ToListAsync();
        }
    }
}

DynamicListExample/Pages/Create.cshtml
@page
@model CreateModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Parent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Parent.Name" class="control-label"></label>
                <input asp-for="Parent.Name" class="form-control" />
                <span asp-validation-for="Parent.Name" class="text-danger"></span>
            </div>
            <div id="newChildDiv"></div>
            <div class="form-group">
                <input id="addNewChildButtonController" type="button" value="Add New Child via Controller" class="btn btn-default" data-url="@Url.Action("GetChildPartialView", "Parent")" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("Shared/_ValidationScriptsPartial");}

    <script type="text/javascript">
        let requestVerificationToken = $("input[name='__RequestVerificationToken']").val();

        $("#addNewChildButtonController").click(function () {
            console.log("Controller Button clicked");
            console.log($("#addNewChildButtonController").data("url"));

            $.ajax({
                type: "GET",
                url: "/Parent/GetChildPartialView",
                headers: {
                    "RequestVerificationToken": requestVerificationToken
                }
            }).done(function (data, statusText, xhdr) {
                console.log("Done");
                $("#newChildDiv").after(data);
            }).fail(function (xhdr, statusText, errorText) {
                console.log("Failed");
                $("#newChildDiv").text(JSON.stringify(xhdr));
            });
        });

        $(document).on('click', '.deleteButton', function(e) {
            e.preventDefault();
            const elementToRemove = document.getElementById(e.target.id).parentNode;

            jQuery(elementToRemove).fadeOut('slow', function () {
                elementToRemove.remove();
            });
        });
    </script>
}

DynamicListExample/Pages/Delete.cshtml
@page
@model DynamicListExample.Pages.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Parent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Parent.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Parent.Name)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Parent.Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

DynamicListExample/Pages/Details.cshtml
@page
@model DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Parent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Parent.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Parent.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Parent.Children)
        </dt>
        @* This doesn't render perfectly, but the data is there *@
        <dd>
            <dl>
                @foreach (var child in Model.Parent.Children)
                {
                    <dt>
                        @Html.DisplayNameFor(model => child.Name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => child.Name)
                    </dd>
                }
            </dl>
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Parent.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

DynamicListExample/Pages/Edit.cshtml
@page
@model EditModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Parent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Parent.Id" />
            <div class="form-group">
                <label asp-for="Parent.Name" class="control-label"></label>
                <input asp-for="Parent.Name" class="form-control" />
                <span asp-validation-for="Parent.Name" class="text-danger"></span>
            </div>
            @foreach (var child in Model.Parent.Children)
            {
                await Html.RenderPartialAsync("Shared/_ChildPartialView", child);
            }
            <div id="newChildDiv"></div>
            <input id="addNewChildButtonController" type="button" value="Add New Child via Controller" class="btn btn-default" data-url="@Url.Action("GetChildPartialView", "Parent")" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("Shared/_ValidationScriptsPartial");}

    <script type="text/javascript">
        let requestVerificationToken = $("input[name='__RequestVerificationToken']").val();

        $("#addNewChildButtonController").click(function () {
            console.log("Controller Button clicked");
            console.log($("#addNewChildButtonController").data("url"));

            $.ajax({
                type: "GET",
                url: "/Parent/GetChildPartialView",
                headers: {
                    "RequestVerificationToken": requestVerificationToken
                }
            }).done(function (data, statusText, xhdr) {
                console.log("Done");
                $("#newChildDiv").after(data);
            }).fail(function (xhdr, statusText, errorText) {
                console.log("Failed");
                $("#newChildDiv").text(JSON.stringify(xhdr));
            });
        });

        $(document).on('click', '.deleteButton', function (e) {
            e.preventDefault();
            const elementToRemove = document.getElementById(e.target.id).parentNode;

            // The lower the number, the faster it goes
            jQuery(elementToRemove).fadeOut('slow', function () {
                elementToRemove.remove();
            });
        });
    </script>
}

DynamicListExample/Pages/Index.cshtml
@page
@model DynamicListExample.Pages.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Parent[0].Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Parent)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>